volumes:
  frontend_node_modules:
  sumo_config:
  database_data:

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - QUART_ENV=development
      - PYTHONPATH=/app/src
    command: ["hypercorn", "src.dashboard:app", "--bind", "0.0.0.0:8080", "--workers", "1"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  sumo:
    container_name: sumo
<<<<<<< HEAD
    build:
      context: ./sumo
      dockerfile: Dockerfile
    # image: camcottle341/smarttransit:latest
=======
    # build:
    #   context: ./sumo
    #   dockerfile: Dockerfile
    image: camcottle341/smarttransit:sumo
>>>>>>> 942221313dde575eed319a7f30c07664ca75f0d8
    ports:
      - "5000:5000"
    volumes:
      - ./sumo/templates:/sumo/templates
    depends_on:
      - backend
