volumes:
  frontend_node_modules:
  database_data:

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - QUART_ENV=development
    command: ["hypercorn", "dashboard:app", "--bind", "0.0.0.0:8080", "--workers", "1"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]
  
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - ./database/.env
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-init.d/schema.sql
      - ./database/test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
    ports:
      - "5432:5432"
