volumes:
  server_node_modules:
  frontend_node_modules:
services:
  # server:
  #   build:
  #     context: ./server
  #   container_name: server
  #   volumes:
  #     - ./server:/app
  #     - server_node_modules:/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./server/.env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"