volumes:
  frontend_node_modules:
  sumo_config:
  database_data:
  shared-output:

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    working_dir: /app/src
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
      - shared-output:/shared/output
    env_file:
      - ./backend/.env
    environment:
      - QUART_ENV=development
    command: ["hypercorn", "dashboard:app", "--bind", "0.0.0.0:8081", "--workers", "1"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

  sumo:
    container_name: sumo
    build:
      context: ./sumo
      dockerfile: Dockerfile
    #image: camcottle341/smarttransit:sumo
    ports:
      - "8008:8080"
    volumes:
      - shared-output:/shared/output
      - ./sumo/templates:/sumo/templates
      - ./sumo/static:/sumo/static
    depends_on:
      - backend